org: chadbartel
app: aws-python-rest-api-project
service: aws-python-rest-api-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.6
  lambdaHashingVersion: '20201221'
  region: us-west-2
  

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
